### ISSUE TITLE
기기 또는 구성요소 없음

### ISSUE THREAD

**Issue by dongsoonpapa** [dugurs/kwh_to_won#10]
에너지 미터를 잘못 설정해서 요금이 잘못책정되는 부분 때문에 유틸리티 미터로 센서 생성후 재등록 하는데
기기를 추가해도 기기 또는 구성요소 없음으로 나옵니다.

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:942
First occurred: 오전 4:35:03 (1 occurrences)
Last logged: 오전 4:35:03

Update for sensor.home_kwhto_forecast fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1259, in async_device_update
    await self.async_update()
  File "/config/custom_components/kwh_to_won/sensor.py", line 419, in async_update
    self.update()
  File "/config/custom_components/kwh_to_won/sensor.py", line 343, in update
    forecast_energy_entity_state = self.hass.states.get(self._forecast_energy_entity).state # 예상사용량센서가 UNKNOWN 상태이면
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'

로그는 이것과

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:344
Integration: 센서 ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 오전 4:34:42 (4 occurrences)
Last logged: 오전 4:40:11

Error while setting up kwh_to_won platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/kwh_to_won/sensor.py", line 89, in async_setup_entry
    ExtendSensor(
  File "/config/custom_components/kwh_to_won/sensor.py", line 250, in __init__
    self.update()
  File "/config/custom_components/kwh_to_won/sensor.py", line 343, in update
    forecast_energy_entity_state = self.hass.states.get(self._forecast_energy_entity).state # 예상사용량센서가 UNKNOWN 상태이면
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'

이런 오류 로그가 뜨네요. 
이전으로 백업본 리스토어도 해보고, 애드온도 삭제후 재설치 해보고 했는데, 증상은 동일합니다.
초보라 잘 몰라서 어떡해야 할지 몰라 질문글 올립니다. 감사합니다.

**Comment by dugurs** [comment]
유틸리티 미터로 만든 센서 상태값을 못 가져 오는것 같습니다.
유틸리티 미터로 만든 센서가 정상적으로 생성되고 업데이트가 되고 있는지 확인 해 주세요.

**Comment by dongsoonpapa** [comment]
답변 감사합니다. 유틸리티미터로 만든 센서 정확하게 값을 가져오고 어찌하다 보니 다시 등록이 됬습니다. 감사합니다. 

한가지만 더 여쭐께요. 구성에서 예상전기 사용량센서랑 전월, 전전월 전기 사용량 센서도 만들려 하는데, 생성이 되질 않습니다. 어떻게 추가를 해야 할까요?

**Comment by dugurs** [comment]
전월사용량센서는 만들고 나서 검침일 이 지나야 갱신이 됩니다. 만든 즉시 값이 업데이트 되지 않습니다. 전전월도 마찬가지 입니다.

**Comment by dongsoonpapa** [comment]
답변 감사합니다^^ 이번달 기다려봐야 겠네요ㅎㅎ 즐거운 저녁되세요~
