### ISSUE TITLE
일부 entity 비활성화 했을때 오류 지속 발생

### ISSUE THREAD

**Issue by n-andflash** [dugurs/kwh_to_won#4]
안녕하세요,

kwh_to_won이 생성하는 4개의 entity 중 1개 이상을 HA에서 "비활성화" 했을 때 6~7초 간격으로 아래 오류가 계속 발생합니다.

```python trackback
ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/kwh_to_won/sensor.py", line 239, in energy_state_listener
self.async_schedule_update_ha_state(True)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 702, in async_schedule_update_ha_state
self.hass.async_create_task(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'async_create_task'
```

아래와 같이 self.enabled 상태일 때만 update 하도록 sensor.py: energy_state_listener() 를 수정하면 해결되는 것으로 보입니다.

```python
def energy_state_listener(self, entity, old_state, new_state):
    """Handle temperature device state changes."""
    if _is_valid_state(new_state):
        self._energy = util.convert(new_state.state, float)
        self._energy_row = self._energy
    if self.enabled:
        self.async_schedule_update_ha_state(True)
```

 소소한 내용이라 그냥 issue로 올립니다... 확인 부탁드려요. 감사합니다.

**Comment by dugurs** [comment]
오류를 재현해 보려고 비활성화 하고 에너지값도 계속 올려보아도 오류가 발생하지 않네요.
카페 문의글에 비슷한 오류가 있었는데, 그분은 전월사용량 센서를 설정해놓은상태에서 전월사용량센서를 삭제하고 삭제한것이 문제를 이르켰었던 케이스 였습니다. 통합구성요소 구성를 지우고 다시 설정하니 해결되었다 하셨습니다.
올려주신 해결책은 위같은 예외 상황에도 적용되는 해결책 인 것 같습니다.
도움 감사드립니다.
