### ISSUE TITLE
재시작시 발생오류

### ISSUE THREAD

**Issue by nara1111** [dugurs/kwh_to_won#7]
안녕하세요,
사용에 문제가 있는 것은 아닌데 재부팅시 아래 오류가 지속적으로 발생하고 있어 일단 보고 드립니다.
string을 float로 변경할 수 없다는 오류인데, 구성 문제가 아니라 py 문제인 듯 하여서요.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 732, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in async_device_update
    await self.async_update()
  File "/config/custom_components/kwh_to_won/sensor.py", line 408, in async_update
    self.update()
  File "/config/custom_components/kwh_to_won/sensor.py", line 364, in update
    ret = self.KWH2WON.kwh2won(forecast_energy, datetime.datetime.now())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kwh_to_won/kwh2won_api.py", line 837, in kwh2won
    energy = float(energy)
             ^^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'

**Comment by dugurs** [comment]
예상사용량 센서보다 커스컴컴포넌트가 먼저 로딩되면서, 예상사용량센서를 읽어오지 못해 나는 에러인데요,
예상사용량센서를 읽지 못할때 에러가 아닌 사용불가로 표시 해보려고 했는데, 왜때문인지 ~~(관련지식부족)~~ 적용이 되질않아 쉽게 포기해버렸습니다 ^^;
너무 늦은 답변 죄송합니다.
